### ISSUE TITLE
Nesting caused vertical white space

### ISSUE THREAD

**Issue by avebeatrix** [le717/jquery-spoiler#8]
Please, fix the problem of extra vertical white space for nested spoilers
![3](https://cloud.githubusercontent.com/assets/20440787/16806014/72a27d80-491b-11e6-8478-0eb731966dba.png)
![1](https://cloud.githubusercontent.com/assets/20440787/16806016/72a338a6-491b-11e6-9836-7e565d495ed9.png)
![2](https://cloud.githubusercontent.com/assets/20440787/16806015/72a2cbf0-491b-11e6-959a-16f6f3a04f31.png)

.

**Comment by le717** [comment]
Can you post the HTML document pictured? It makes it easier for me to recreate.

Did you try setting `includePadding: false` in the options?

**Comment by avebeatrix** [comment]
Use includePadding: false.
`<html>
<head>
</head>
<body>
 <div class="spoiler" id="spoiler-text" data-spoiler-link="1"><span>Spoiler 1</span></div>
<div class="spoiler-content" data-spoiler-link="1">
  <blockquote  class="spoiler"  data-spoiler-link="2">"...Every day the same thing: Variety. I want something different! Fix me hasenpfeffer right away!" That honorable, royal, majestic, graciousness</blockquote>
  <div class="spoiler-content" data-spoiler-link="2">
	  <blockquote  class="spoiler"  data-spoiler-link="3">"...Every day the same thing: Variety. I want something different! Fix me hasenpfeffer right away!" That honorable, royal, majestic, graciousness</blockquote>
	  <div class="spoiler-content" data-spoiler-link="3">
		  <blockquote>"...Every day the same thing: Variety. I want something different! Fix me hasenpfeffer right away!" That honorable, royal, majestic, graciousness</blockquote>
		</div>
	</div>
</div>
<div class="spoiler" id="spoiler-text" data-spoiler-link="6"><span>Spoiler 2</span></div>
<div class="spoiler-content" data-spoiler-link="6">
  <blockquote  class="spoiler"  data-spoiler-link="4">"...Every day the same thing: Variety. I want something different! Fix me hasenpfeffer right away!" That honorable, royal, majestic, graciousness</blockquote>
  <div class="spoiler-content" data-spoiler-link="4">
	  <blockquote>"...Every day the same thing: Variety. I want something different! Fix me hasenpfeffer right away!" That honorable, royal, majestic, graciousness</blockquote>
	</div>
</div>
 <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>  
  <script src="jquery.spoiler.js"></script>
  <script>
    jQuery(function() {
		  "use strict";
		  // Activate jQuery Spoiler
		  jQuery(".spoiler").spoiler({includePadding: false, triggerEvents: true});
	  	
    });
	
	
  </script>
  <style type="text/css">
	blockquote{margin:0;}
  </style>
</body>
</html>`

**Comment by avebeatrix** [comment]
Did my task with the help of triggers

```javascript
jQuery(".spoiler").on("jq-spoiler-visible", function() {
			
			  var spoiler  = $(this).attr("data-spoiler-link"),
			  $content = $(".spoiler-content[data-spoiler-link=" + spoiler + "]");
			  
			  var contentHeight = 0;
			   $.each($('>*',$content), function(){
				if (!$(this).hasClass('spoiler-content')){
					contentHeight += $(this).height();		
					
				}
			  })
			
			  $content.height(contentHeight);
		  
			var contentHeight2 = [];
			contentHeight2[0]=contentHeight;
			var i=1;
			$.each($content.parents('.spoiler-content'), function(){
				contentHeight2[i] = 0;
				$.each($('>*',$(this)), function(){
					if (!$(this).hasClass('spoiler-content')){
						contentHeight2[i] += $(this).height();		
						
					}
				})
			
				contentHeight2[i]+=contentHeight2[i-1];				
			  
				$(this).height(contentHeight2[i]);
				i++;
			})
		  		  		  		  	
		});
		jQuery(".spoiler").on("jq-spoiler-hidden", function() {
		  // Perform action
		  
		 var spoiler  = $(this).attr("data-spoiler-link"),
          $content = $(".spoiler-content[data-spoiler-link=" + spoiler + "]");
		  
		  $(".spoiler-content", $content).css({"height": "0"}).removeClass('spoiler-content-visible');
		  $(".spoiler-active", $content).removeClass('spoiler-active');		 
		  
		  var contentHeight2 = [];
			contentHeight2[0]=0;
			var i=1;
			$.each($content.parents('.spoiler-content'), function(){
				contentHeight2[i] = 0;
				$.each($('>*',$(this)), function(){
					if (!$(this).hasClass('spoiler-content')){
						contentHeight2[i] += $(this).height();		
						
					}
				})
				
				contentHeight2[i]+=contentHeight2[i-1];				
			  
				$(this).height(contentHeight2[i]);
				i++;
			})
		 
		 
		});

```
